#
#	Makefile for the library <lib> and testprogramm <test>.
#
#	$Log: not supported by cvs2svn $
#

include	$(HOME)/EVOS+/EVOSplus1.mk

LIBLOCAL=
LIBS	=

LLOCAL	=
LLIBS	=

PRG	=
PRGPURE	=

PRGSRC	=
PRGOBJ	=

SRCS	=
OBJS	= $(LIBLOCAL)($(SRCS:.c=.o) )

include	$(HOME)/EVOS+/EVOSplus2.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
