#
#	Makefile for the library librst.a.
#
#	$Log: not supported by cvs2svn $
# Revision 1.1  1994/06/06  13:53:03  schuetz
# Initial revision
#
# Revision 1.1  1994/06/06  13:53:03  schuetz
# Initial revision
#
#

include	$(HOME)/Entwicklung/EVOS+/EVOS+1.mk

LIBLOCAL= $(LIB)/librst.a
LIBS	= 

LLOCAL	=
LLIBS	=

PRG	=
PRGPURE	=

PRGSRC	=
PRGOBJ	=

SRCS	= rst.c nullRst.c nacaRst.c reflectionRst.c standard.c
OBJS    = $(LIBLOCAL)($(SRCS:.c=.o) )

include	$(HOME)/Entwicklung/EVOS+/EVOS+2.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
