#
#	Makefile for the library librst.a.
#
#	$Log: not supported by cvs2svn $
# Revision 1.1  1994/06/06  13:53:03  schuetz
# Initial revision
#
# Revision 1.1  1994/06/06  13:53:03  schuetz
# Initial revision
#
#

include	$(HOME)/Entwicklung/EVOS+/EVOS+1.mk

LIBLOCAL= $(LIB)/libmain.a
LIBS	=
#$(LIB)/librng.a       \
#	  $(LIB)/libutil.a      \
#	  $(LIB)/libtyp.a

LLOCAL	= -lmain
LLIBS	=
#-lRNG -lutil -ltyp

PRG	= main
PRGPURE	= main.purify

PRGSRC	= 
PRGOBJ	=

ifeq ($(PVM),YES)
SRCS	= create.c data.c eval.c fio.c gnup.c init.c input.c \
	  migration.c params.c pars.c report.c send.c slct.c term.c util.c
else
SRCS	= create.c data.c eval.c fio.c gnup.c init.c input.c \
	  migration.c params.c pars.c report.c slct.c term.c util.c
endif
OBJS    = $(LIBLOCAL)($(SRCS:.c=.o) )

include	$(HOME)/Entwicklung/EVOS+/EVOS+2.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.

//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/time.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/_ansi.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/newlib.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/sys/config.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/machine/ieeefp.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/sys/reent.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/sys/_types.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/machine/time.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/sys/types.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/machine/types.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(init.o): /usr/include/sys/features.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/stdlib.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/_ansi.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/newlib.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/sys/config.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/machine/ieeefp.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/sys/reent.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/sys/_types.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/machine/stdlib.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(input.o): /usr/include/alloca.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(term.o): /usr/include/term.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(term.o): /usr/include/ncurses/ncurses_dll.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(term.o): /usr/include/termios.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(term.o): /usr/include/sys/termios.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/math.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/sys/reent.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/_ansi.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/newlib.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/sys/config.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/machine/ieeefp.h
//server1/schuetz/Entwicklung/EVOS+/lib/libmain.a(util.o): /usr/include/sys/_types.h
