#
#	Makefile for the library libtop.a.
#
#	$Log: not supported by cvs2svn $
#
#
#

include	$(HOME)/Entwicklung/EVOS+/EVOS+1.mk

LIBLOCAL= $(LIB)/libtop.a
LIBS	= $(LIB)/librng.a	\
	  $(LIB)/libtyp.a	\
	  $(LIB)/libutil.a

LLOCAL	= -ltop
LLIBS	= -lrng -ltyp -lutil

PRG	= topology
PRGPURE	= topology.purify

PRGSRC	= #main.c
PRGOBJ	= #main.o

SRCS	= topology.c circle.c null.c #rectangle.c
OBJS    = $(LIBLOCAL)($(SRCS:.c=.o) )
#rectangle.o

include	$(HOME)/Entwicklung/EVOS+/EVOS+2.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.



circle.o): /server1/home5/schuetz/EVOS+/inc/define.h
circle.o): /server1/home5/schuetz/EVOS+/inc/getparm.h
circle.o): /server1/home5/schuetz/EVOS+/inc/ind.h
circle.o): /server1/home5/schuetz/EVOS+/inc/migration.h
circle.o): /server1/home5/schuetz/EVOS+/inc/panic.h
circle.o): /server1/home5/schuetz/EVOS+/inc/pop.h
circle.o): /server1/home5/schuetz/EVOS+/inc/send.h
circle.o): /server1/home5/schuetz/EVOS+/inc/topology.h
circle.o): /server1/home5/schuetz/EVOS+/inc/types.h
circle.o): /server1/home5/schuetz/EVOS+/inc/vector.h /usr/include/alloca.h
circle.o): /usr/include/asm/errno.h /usr/include/bits/endian.h
circle.o): /usr/include/bits/errno.h /usr/include/bits/local_lim.h
circle.o): /usr/include/bits/posix1_lim.h /usr/include/bits/posix2_lim.h
circle.o): /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
circle.o): /usr/include/bits/select.h /usr/include/bits/sigset.h
circle.o): /usr/include/bits/stdio_lim.h /usr/include/bits/time.h
circle.o): /usr/include/bits/types.h /usr/include/bits/xopen_lim.h
circle.o): /usr/include/endian.h /usr/include/errno.h /usr/include/features.h
circle.o): /usr/include/gnu/stubs.h /usr/include/limits.h
circle.o): /usr/include/linux/errno.h /usr/include/linux/limits.h
circle.o): /usr/include/malloc.h /usr/include/stdlib.h
circle.o): /usr/include/sys/cdefs.h /usr/include/sys/select.h
circle.o): /usr/include/sys/sysmacros.h /usr/include/sys/time.h
circle.o): /usr/include/sys/types.h /usr/include/time.h /usr/include/xlocale.h
circle.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
circle.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
circle.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
circle.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
circle.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/varargs.h
circle.o): /usr/lib/pvm3/include/pvm3.h
null.o): /server1/home5/schuetz/EVOS+/inc/define.h
null.o): /server1/home5/schuetz/EVOS+/inc/ind.h
null.o): /server1/home5/schuetz/EVOS+/inc/migration.h
null.o): /server1/home5/schuetz/EVOS+/inc/panic.h
null.o): /server1/home5/schuetz/EVOS+/inc/pop.h
null.o): /server1/home5/schuetz/EVOS+/inc/send.h
null.o): /server1/home5/schuetz/EVOS+/inc/topology.h
null.o): /server1/home5/schuetz/EVOS+/inc/types.h
null.o): /server1/home5/schuetz/EVOS+/inc/vector.h /usr/include/alloca.h
null.o): /usr/include/asm/errno.h /usr/include/bits/endian.h
null.o): /usr/include/bits/errno.h /usr/include/bits/local_lim.h
null.o): /usr/include/bits/posix1_lim.h /usr/include/bits/posix2_lim.h
null.o): /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
null.o): /usr/include/bits/select.h /usr/include/bits/sigset.h
null.o): /usr/include/bits/stdio_lim.h /usr/include/bits/time.h
null.o): /usr/include/bits/types.h /usr/include/bits/xopen_lim.h
null.o): /usr/include/endian.h /usr/include/errno.h /usr/include/features.h
null.o): /usr/include/gnu/stubs.h /usr/include/limits.h
null.o): /usr/include/linux/errno.h /usr/include/linux/limits.h
null.o): /usr/include/malloc.h /usr/include/stdlib.h /usr/include/sys/cdefs.h
null.o): /usr/include/sys/select.h /usr/include/sys/sysmacros.h
null.o): /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/time.h
null.o): /usr/include/xlocale.h
null.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
null.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
null.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
null.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
null.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/varargs.h
null.o): /usr/lib/pvm3/include/pvm3.h
topology.o): /server1/home5/schuetz/EVOS+/inc/define.h
topology.o): /server1/home5/schuetz/EVOS+/inc/ind.h
topology.o): /server1/home5/schuetz/EVOS+/inc/migration.h
topology.o): /server1/home5/schuetz/EVOS+/inc/panic.h
topology.o): /server1/home5/schuetz/EVOS+/inc/pop.h
topology.o): /server1/home5/schuetz/EVOS+/inc/send.h
topology.o): /server1/home5/schuetz/EVOS+/inc/topology.h
topology.o): /server1/home5/schuetz/EVOS+/inc/types.h
topology.o): /server1/home5/schuetz/EVOS+/inc/vector.h /usr/include/alloca.h
topology.o): /usr/include/asm/errno.h /usr/include/bits/endian.h
topology.o): /usr/include/bits/errno.h /usr/include/bits/local_lim.h
topology.o): /usr/include/bits/posix1_lim.h /usr/include/bits/posix2_lim.h
topology.o): /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
topology.o): /usr/include/bits/select.h /usr/include/bits/sigset.h
topology.o): /usr/include/bits/stdio_lim.h /usr/include/bits/time.h
topology.o): /usr/include/bits/types.h /usr/include/bits/xopen_lim.h
topology.o): /usr/include/endian.h /usr/include/errno.h
topology.o): /usr/include/features.h /usr/include/gnu/stubs.h
topology.o): /usr/include/limits.h /usr/include/linux/errno.h
topology.o): /usr/include/linux/limits.h /usr/include/malloc.h
topology.o): /usr/include/stdlib.h /usr/include/sys/cdefs.h
topology.o): /usr/include/sys/select.h /usr/include/sys/sysmacros.h
topology.o): /usr/include/sys/time.h /usr/include/sys/types.h
topology.o): /usr/include/time.h /usr/include/xlocale.h
topology.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
topology.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
topology.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
topology.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
topology.o): /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/varargs.h
topology.o): /usr/lib/pvm3/include/pvm3.h
